<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<head>
		<title>Visual LightBox Gallery generated by VisualLightBox.com</title>
		<meta http-equiv="content-type" content="text/html;charset=utf-8" />
		<meta name="keywords" content="VisualLightBox, LightBox, Photo Gallery, lightbox web gallery generator, best lightbox gallery" />
		<meta name="description" content="Visual LightBox Gallery created with VisualLightBox, a free wizard program that helps you easily generate beautiful Lightbox-style web photo galleries" />
				<!-- Start VisualLightBox.com HEAD section -->
		
		<link rel="stylesheet" href="galeria/index_files/vlb_files1/vlightbox1.css" type="text/css" />
		<link rel="stylesheet" href="galeria/index_files/vlb_files1/visuallightbox.css" type="text/css" media="screen" />
        <script src="galeria/index_files/vlb_engine/jquery.min.js" type="text/javascript"></script>
		<script src="galeria/index_files/vlb_engine/visuallightbox.js" type="text/javascript"></script>
		<!-- End VisualLightBox.com HEAD section -->

	</head>
	<body bgcolor="#000">
		<!-- Start VisualLightBox.com BODY section id=1 -->
	
	<div id="vlight">
	
	<ul>

	
		<?php 
	
						
					$pag  = (empty($_GET['pag']) ? '1' : $_GET['pag']);
					$maximo  = 16 ;
					$inicio  = ($pag * $maximo) - $maximo;
					$nome    = $_GET['nome'];
				    $id      = $_GET['id'];
                 //selecione foto usuario quando nome do usuario = foto e id_pai = id
                     $gal = mysql_query("select * from ppg_play where nome='$nome' order by id desc");

                     while($ga = mysql_fetch_array($gal)){


?>

<li>	
	
<a class="vlightbox1" href="time/upload/<?php echo $ga['foto']?>"  title="">
	
<img src="time/upload/<?php echo $ga['foto']?>"  height="120" width="170"  alt=""/>
</a>
</li>
	
	
	<?php }?>

	<?php
	                    $id = $_GET['id'];
					
					     $link = 'http://rgpsico.comuv.com/single.php?id='.$id.'&pag=';
			             readPaginator('galeria',"WHERE id_pai" , $maximo, $link ,$pag);
						
						 
					?>
	
	<!--<a class="vlightbox1" href="galeria/index_files/vlb_images1/100_1565.jpg" title="100_1565">
	
	<img src="galeria/index_files/vlb_thumbnails1/100_1565.jpg" alt="100_1565"/>
	</a>-->
	
	
   


</ul>


	</div>
	</div>
	
	
	
	
	<script src="galeria/index_files/vlb_engine/vlbdata1.js" type="text/javascript"></script>
	<!-- End VisualLightBox.com BODY section -->

	</body>
</html>
